# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.14
    working_directory: ~/voir-et-localiser-samu-sign-on
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run test:lint
  deploy:
    docker:
      - image: circleci/node:8.14
    working_directory: ~/voir-et-localiser-samu-sign-on
    steps:
      - run: |
          mkdir --parents ~/.ssh
          touch ~/.ssh/known_hosts
          echo '|1|mlL85t89J2gurDbrEZ6KiY/5qw8=|N/r6RUzUY4QM+8HcuPBCZEbpxos= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBP79yIilaQAMoztXmfjp4SRRV8p2tmjA8B/6NCtzWU4y0Icu50e5zN20pp8X5zRivsDz2ci6XiTGPaAHCYGDfjI=' >> ~/.ssh/known_hosts
          echo '|1|GmMAqn9UNbCDzYY++lc7WMPayF0=|UaTDUhMKImeQbRvzL7IevkceJrI= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBP79yIilaQAMoztXmfjp4SRRV8p2tmjA8B/6NCtzWU4y0Icu50e5zN20pp8X5zRivsDz2ci6XiTGPaAHCYGDfjI=' >> ~/.ssh/known_hosts
          $DEPLOY_COMMAND
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
